export const ANALYTICS = "Analytics"
export const TRANSACTIONS = "Transactions"
export const BUDGETS = "Budgets"
export const HELLO = 'Hello'
export const LOGOUT = 'Logout'
export const CANCEL = 'Cancel'
export const UPDATE = 'Update'
export const EDIT_EXPENSE = 'Edit Expense'
export const REMAINING_BALANCE = 'Remaining Balance: '
export const DAILY_SPENDING = 'Daily Spending: '
export const ADD = 'Add'